### ISSUE TITLE
Erro "Peer disconnected after first handshake message"

### ISSUE THREAD

**Issue by jarjar123** [DeveloperCielo/Webservice-1.5#1]
Olá! Saberia dizer do que se trata este erro? E como resolver?
![erro](https://cloud.githubusercontent.com/assets/3688798/8439280/61bc58ce-1f41-11e5-8d14-85c666f4e5f7.png)
Obrigado, e boa semana!

**Comment by netojoaobatista** [comment]
Esse erro está na versão incorreta do protocolo TLS, utilizado pelo seu navegador. Será necessário fazer a atualização.
