### ISSUE TITLE
Código de erro "GD" faltando

### ISSUE THREAD

**Issue by hugomaiavieira** [DeveloperCielo/Webservice-1.5#11]
Recebi o código de erro "GD", que não está presente na documentação. Ligando no suporte, foi informado que se trata de um erro onde o banco faz o bloqueio por motivos de segurança.

**Comment by netojoaobatista** [comment]
@hugomaiavieira, houve uma atualização recente nos códigos; vou verificar se houve a adição desse `GD` e atualizo a docucmentação.

:smile:

**Comment by hugomaiavieira** [comment]
O código foi adicionado à documentação nesse commit 6489fd7
