### ISSUE TITLE
Merchant ID different length

### ISSUE THREAD

**Issue by nvnvenki** [DeveloperCielo/Webservice-1.5#13]
We are trying to integrate one of our product to use cielo payment gateway. We had created the the integration using the doc
https://www.cielo.com.br/wps/wcm/connect/c682298e-4518-4e2b-8945-cef23e04b5ec/Cielo-E-commerce-Manual-do-Desenvolvedor-WebService-PT-V2.5.4.pdf?MOD=AJPERES&CONVERT_TO=url

as per the doc its showing the mechant id field should be less than 20 characters.

When I registered using https://cadastrosandbox.cieloecommerce.cielo.com.br

I got the merchant ID which is more than 20 characters. Because of that when we call cielo api with base url as https://qasecommerce.cielo.com.br/servicos/ecommwsec.do service url we are getting error about xsd validation on merchant ID field.
Is there any portal where we can register as merchant of old apis? Please advise.

**Comment by netojoaobatista** [comment]
@nvnvenki, there are 2 different APIs:

1. The `Webservice 1.5`, which is the one you have integrated; 
2. The `API 3.0`, which is the one you got the credential with different length;

To use the test environment, please, use the test credentials as shown in the manual: https://developercielo.github.io/Webservice-1.5/english.html#testing-and-homologation

:smile:

**Comment by nvnvenki** [comment]
I tried the sample
By sending the request through mensagem variable.


curl -X POST \
  https://qasecommerce.cielo.com.br/servicos/ecommwsec.do \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/x-www-form-urlencoded' \
  -d mensagem=<requisicao-transacao id="2520316e-1a37-4afa-94f2-d3db9c3acae5" versao="1.2.1" xmlns="http://www.example.org"><dados-ec><numero>1006993069</numero><chave>25fbb99741c739dd84d7b06ec78c9bac718838630f30b112d033ce2e621b34f3</chave></dados-ec><dados-portador><numero>4012001037141112</numero><validade>201805</validade><indicador>1</indicador><codigo-seguranca>123</codigo-seguranca><nome-portador>System Administrator</nome-portador></dados-portador><dados-pedido><numero>1495635182271</numero><valor>100</valor><moeda>840</moeda><data-hora>2017-05-24T07:13:02.302-07:00</data-hora><descricao>Authorization for 100</descricao><idioma>EN</idioma></dados-pedido><forma-pagamento><produto>1</produto><parcelas>1</parcelas></forma-pagamento><autorizar>3</autorizar><capturar>false</capturar><bin>401200</bin><gerar-token>true</gerar-token></requisicao-transacao>


Got the below response. Not sure what I'm missing please help.
I see that xml I'm sending is valid.

<?xml version="1.0" encoding="ISO-8859-1"?>
<erro xmlns="http://ecommerce.cbmp.com.br" id="">
    <codigo>001</codigo>
    <mensagem>
        <![CDATA[
O XML informado não é valido:
- Invalid type: '<requisicao-transacao id="2520316e-1a37-4afa-94f2-d3db9c3acae5" versao="1.2.1" xmlns="http://www.example.org"><dados-ec><numero>1006993069</numero><chave>25fbb99741c739dd84d7b06ec78c9bac718838630f30b112d033ce2e621b34f3</chave></dados-ec><dados-portador><numero>4012001037141112</numero><validade>201805</validade><indicador>1</indicador><codigo-seguranca>123</codigo-seguranca><nome-portador>System Administrator</nome-portador></dados-portador><dados-pedido><numero>1495635182271</numero><valor>100</valor><moeda>840</moeda><data-hora>2017-05-24T07:13:02.302-07:00</data-hora><descricao>Authorization for 100</descricao><idioma>EN</idioma></dados-pedido><forma-pagamento><produto>1</produto><parcelas>1</parcelas></forma-pagamento><autorizar>3</autorizar><capturar>false</capturar><bin>401200</bin><gerar-token>true</gerar-token></requisicao-transacao>'
]]>
</mensagem>
</erro>

**Comment by netojoaobatista** [comment]
Okay, we have 2 problems here:

* 1st - you're using the `xmlns="http://www.example.org"` namespace that Cielo's API doesn't understand. You shold use `xmlns="http://ecommerce.cbmp.com.br" `, that is the correct namespace.
* 2nd - as you're using the version 1.2.1, you should send the card issuer on the `<forma-pagamento>` node using the element `<bandeira>`.

Please, try this:

```bash
curl https://qasecommerce.cielo.com.br/servicos/ecommwsec.do \
-H 'content-type: application/x-www-form-urlencoded' \
-d 'mensagem=<?xml version="1.0" encoding="ISO-8859-1"?>
<requisicao-transacao xmlns="http://ecommerce.cbmp.com.br" id="2520316e-1a37-4afa-94f2-d3db9c3acae5" versao="1.2.1">
  <dados-ec>
    <numero>1006993069</numero>
    <chave>25fbb99741c739dd84d7b06ec78c9bac718838630f30b112d033ce2e621b34f3</chave>
  </dados-ec>
  <dados-portador>
    <numero>4012001037141112</numero>
    <validade>201805</validade>
    <indicador>1</indicador>
    <codigo-seguranca>123</codigo-seguranca>
    <nome-portador>System Administrator</nome-portador>
  </dados-portador>
  <dados-pedido>
    <numero>1495635182271</numero>
    <valor>100</valor>
    <moeda>840</moeda>
    <data-hora>2017-05-24T07:13:02.302-07:00</data-hora>
    <descricao>Authorization for 100</descricao>
    <idioma>EN</idioma>
  </dados-pedido>
  <forma-pagamento>
    <bandeira>visa</bandeira>
    <produto>1</produto>
    <parcelas>1</parcelas>
  </forma-pagamento>
  <autorizar>3</autorizar>
  <capturar>false</capturar>
  <bin>401200</bin>
  <gerar-token>true</gerar-token>
</requisicao-transacao>'
```

Also, please, tell me: what language/technology are you using in this integration?

**Comment by nvnvenki** [comment]
Thanks a lot!
It's working now.

We are using Oracle SOA for the development of the integration.

**Comment by netojoaobatista** [comment]
Nice!

If you have any other issue, please, just ask.

:smile:
