### ISSUE TITLE
JSON

### ISSUE THREAD

**Issue by magusd** [DeveloperCielo/Webservice-1.5#2]
Olá,

Vocês tem previsão para implantar respostas em JSON?
Trabalho com desenvolvimento mobile e javascript, XML é realmente uma dor de cabeça.

Obrigado!

**Comment by allisson** [comment]
Acredito que isso vai ser resolvido no https://developercielo.github.io/Webservice-3.0/, mas acredito que essa api 3.0 ainda não está em operação.
