### ISSUE TITLE
Acesso aos endpoints usando um servidor estrangeiro

### ISSUE THREAD

**Issue by allisson** [DeveloperCielo/Webservice-1.5#3]
Olá,

Eu tenho servidor na Linode e estou sem conseguir acessar os endpoints do webservice 1.5 da Cielo.

Localmente (com um ip do Brasil) eu acesso sem problemas, mas a partir do servidor de produção sempre ocorre erro de comunicação e a requisição nunca é completada.

Outras pessoas já passam por esse mesmo problema: http://forum.imasters.com.br/topic/436693-erro-em-curl-exec-na-loja-exemplo-da-cielo/

**Comment by xthiago** [comment]
Olá Allison,

Você não consegue nem fazer um ping no endpoint deles?

No dia 08/01/16 a Cielo atualizou o seu certificado SSL. É necessário atualizá-lo na TrustedStore do servidor. Mais info: https://developercielo.github.io/Webservice-1.5/#como-instalar-o-certificado-extended-validation-no-servidor-da-loja?

Tenho um servidor em Nova York e está se comunicando normalmente. :)

Abraço

**Comment by allisson** [comment]
Eu resolvi o problema forçando as requisições a usar o TLSv1.

Eu criei essa lib para trabalhar com python: https://github.com/allisson/python-cielo-webservice

E esse commit resolveu: https://github.com/allisson/python-cielo-webservice/commit/ac825064e7d9361b096c90abd94288a50e204376

Obrigado.

**Comment by netojoaobatista** [comment]
@allisson, sua lib está funcionando redondinha? Se estiver, e você permitir, vou fazer um fork dela aqui no perfil da Cielo.

**Comment by allisson** [comment]
Estou usando ela sem problemas em um projeto de ecommerce aqui na empresa, ainda falta um tempinho para melhorar a documentação.

Pode fazer o fork :+1:

**Comment by netojoaobatista** [comment]
Legal, @allisson!

Fork feito!

:smile:
