### ISSUE TITLE
Dúvida com o nome da loja e da chave

### ISSUE THREAD

**Issue by weversontaxoto** [DeveloperCielo/Webservice-1.5#4]
Boa tarde !

Não encontrei um lugar oportuno para setar o numero da loja e a sua chave. Então pela analise na "loja exemplo" a pagina mais indicada para setar os valores acredito que seja a "novoPedidoAguarde.jsp", nela adiciono o seguinte código java:

           Pedido pedido = new WebUtils(request).criarPedido(); // Código já existente

           Loja loja = new Loja(1000000, "chave"); // Código adicionado

           pedido.setLoja(loja); // Código adicionado

           Porem após colocar esses valores e alterar a URL para a base de homologação, continua aparecendo o erro "2 Credenciais inválidas" e as vezes erro 500.

           Vocês conseguem me ajudar de alguma forma ?

**Comment by netojoaobatista** [comment]
Por favor, abra sua issue no repositório correspondente ao código que está utilizando. Esse repositório aqui é da documentação geral e não envolve código de integração.

**Comment by weversontaxoto** [comment]
Ok, postei aqui porque a CIELO enviou exatamente este link, desculpe, já fiz o acerto.
