### ISSUE TITLE
Schema do Arquivo de Lote

### ISSUE THREAD

**Issue by gabrielrios** [DeveloperCielo/Webservice-1.5#8]
Na documentação para o envio de arquivos de lote é mencionado um arquivo (ecm-lote.xsd), porém não consigo encontra-lo para baixar.

**Comment by ederlopes** [comment]
Neto, encontrei dificuldades em acessar o Objeto Authentication para buscar a informação quando há falha na autenticação do usuário, então adicionei na  classe Cielo\Consultation.php e funcionou perfeitamente. Verifique esta possibilidade caso esteja fazendo algo errado favor desprezar esta issue.

public function getAuthentication()
{
        return $this->authentication;
}

**Comment by netojoaobatista** [comment]
Foi adicionado no [repositório do processamento em lotes](https://github.com/DeveloperCielo/Webservice-1.5-Processamento-em-lote/commit/2997a3420c976630f8df069cfa8258d1bdf4e711).
