### ISSUE TITLE
Acesso ao objeto Authentication para transação com autenticação

### ISSUE THREAD

**Issue by ederlopes** [DeveloperCielo/Webservice-1.5#9]
Neto, encontrei dificuldades em acessar o Objeto Authentication para buscar a informação quando há falha na autenticação do usuário, então adicionei na classe Cielo\Consultation.php e funcionou perfeitamente. Verifique esta possibilidade caso esteja fazendo algo errado favor desprezar esta issue.

public function getAuthentication()
{
return $this->authentication;
}

**Comment by netojoaobatista** [comment]
@ederlopes, por favor, coloque sua dúvida no repositório adequado. Aqui é o repositório da documentação e você está colocando uma dúvida sobre implementação PHP. Postar dúvidas offtopic nos repositórios prejudica outros devs.
